version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: bookstore-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bookstore
    volumes:
      - mongodb_data:/data/db
    networks:
      - bookstore-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build: 
      context: ./bookstore-app-backend
      dockerfile: Dockerfile
    container_name: bookstore-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=bookstore
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - bookstore-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: 
      context: ./bookstore-app-frontend
      dockerfile: Dockerfile
    container_name: bookstore-frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - API_HOST=backend
      - API_PORT=5000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local