# k8s/02-mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: bookstore
type: Opaque
data:
  # Default values - replace with your actual credentials (base64 encoded)
  # MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # admin
  # MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  # password
  # For this example, we'll use a simple setup without authentication
  mongodb-uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvYm9va3N0b3Jl  # mongodb://mongodb:27017/bookstore